### ISSUE TITLE
PropertySortOrderFix does not respect `order` settings

### ISSUE THREAD

**Issue by squ1b3r** [idok/scss-lint-plugin#11]
Despite the fact that I have specified `concentric` order when I press `alt + enter` and chose "Sort Properties" the plugin sorts everything alphabetically anyway.
```
  PropertySortOrder:
    enabled: true
    order: concentric
    ignore_unspecified: false
    separate_groups: false
```
