### ISSUE TITLE
Plugin always suggests single quoted strings regardless of settings

### ISSUE THREAD

**Issue by G-Rath** [idok/scss-lint-plugin#64]
### Versions

scss-lint version: scss-lint 0.57.1

IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
Licensed to Gareth Jones
Subscription is active until June 22, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

### Description

Working on a fairly standard rails application, generating in the typical way.

Using `.sass-lint.yml` file with the following:

```
files:
  include: "**/*.s+(a|c)ss"
  ignore:
    - "app/assets/stylesheets/foundation_and_overrides.scss"
    - "app/assets/stylesheets/_settings.scss"
    - "node_modules/**/*"
options:
  formatter: stylish
  # Default rules are visible at
  #
  #   https://github.com/sasstools/sass-lint/blob/develop/lib/config/sass-lint.yml
  #
  # We choose to accept them and tweak them in the 'rules' section below
  merge-default-rules: true

rules:
  quotes:
    - 1
    - style: double
  class-name-format:
    - 1
    - convention: hyphenatedbem
  final-newline:
    - 0
  nesting-depth:
    - 1
    - max-depth: 3
  no-vendor-prefixes: 0
  no-color-literals: 0
  placeholder-in-extend: 0
```

Have a file called `application.scss` located at `app/assets/stylesheets/` with the following:

```
@import "foundation_and_overrides";
@import "selectize.default";
@import "flatpickr/dist/flatpickr";
@import "base/buttons";
@import "base/containers";
@import "base/errors";
@import "base/fonts";
@import "base/icons";
@import "base/print";
```

(Actually has 75 imports total, but they all look like the above, and nothing else is in the file).

### Steps to Reproduce

1. Generate standard rails application
2. Create `.sass-lint.yml` with content mentioned above
4. Set plugin to look for `.sass-lint.yml` specifically
3. Create `application.scss` with content mentioned above

**Expected behavior:** No warnings from `scss-lint`

**Actual behavior:** `scss-lint` warns about preferring single quoted strings.

I'm fairly new to ruby & scss-lint, so it's possible that I've missed something really obvious.
This is the linting rule file provided by the company I work for, who have previously never had a developer working with IntelliJ.

Please let me know if there's any more information I can provide.
